added todolist app for week1-react homework
TITHI1244/hyf-homework pull request #21
Opened 2021-02-22 09:39 UTC by TITHI1244

2021-02-26 16:49 UTC, Ekamba requested changes
Hi @TITHI1244 , great work so far. But remember when you are rendering a list of items you have to specify a key. You can read more about list key here: https://reactjs.org/docs/lists-and-keys.html

2021-02-27 15:54 UTC, khjcph commented on react/week1/todo_list/src/Header.js
> +        <div>
you actually don't need to put this inside a `div`

2021-02-27 15:54 UTC, khjcph commented on react/week1/todo_list/src/ListItem.js
> +function ListItem(props) {
When passing props, you can actually use a very cool javascript feature called destructuring. For example

    const ListItems = ({description, deadline}) => { }

Then you can access the variables without using `props.`

2021-02-27 15:58 UTC, khjcph commented on react/week1/todo_list/src/App.js
> +          {todos.map(todo => <ListItem title={todo.title} deadline={todo.deadline} />)}
I don't know if this was covered in class, but lists in react should actually have a unique key. You can read more about those here: https://reactjs.org/docs/lists-and-keys.html#keys. If you would like to you can try to implement keys for your list.

2021-02-27 15:59 UTC, khjcph approved these changes
Great work!! 👍

I left a few comments that you can look at if you want. I don't remember if we covered destructuring in class. If not, you can just ignore that.

2021-03-15 22:05 UTC, TITHI1244 commented
Thank you for your feedback @Ekamba & @khjcph. I have changed them :)

2021-03-15 22:25 UTC, merged